language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install coverage --use-mirrors"
before_script:
  - source env.sh
  - export PYTHONPATH="$PYTHONPATH:."
script:
  - nosetests --with-coverage --cover-package=qiniu
  - python docs/demo.py
  - python docs/gist/conf.py
