language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - export QINIU_ACCESS_KEY="X0XpjFmLMTJpHB_ESHjeolCtipk-1U3Ok7LVTdoN"
  - export QINIU_SECRET_KEY="wenlwkU1AYwNBf7Q9cCoG4VT_GYyrHE9AS_R2u81"
  - export QINIU_BUCKET_NAME="pysdk"
  - export QINIU_DOMAIN="pysdk.qiniudn.com"
  - export PYTHONPATH="$PYTHONPATH:."
script:
  - python setup.py nosetests
  - python docs/demo.py
  - python docs/gist/conf.py
